image: registry.gitlab.com/apurebase/connect/jdk:latest

stages:
  - test
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - build
    - .gradle


########
# Jobs #
########

test:
  stage: test
  script:
    - ./gradlew check --no-daemon
    - chmod +x ./scripts/coverage.sh
    - ./scripts/coverage.sh

build:
  stage: build
  script: ./gradlew --build-cache assemble --no-daemon

