image: gradle:alpine

stages:
  - test
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - build
    - .gradle


########
# Jobs #
########

test:
  stage: test
  script:
    - gradle check
    - chmod +x ./scripts/coverage.sh
    - ./scripts/coverage.sh

build:
  stage: build
  script: gradle --build-cache assemble

