image: adoptopenjdk/openjdk8-openj9:alpine

stages:
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - build
    - .gradle


########
# Jobs #
########

build:
  stage: test
  script: ./gradlew --build-cache assemble

test:
  stage: test
  script:
    - ./gradlew check --no-daemon
    - chmod +x ./scripts/coverage.sh
    - ./scripts/coverage.sh
