version: '3.7'

services:
  docs:
    image: jeggy/arkenv-docs
    networks:
      - public
    deploy:
      labels:
        traefik.http.routers.arkenv.rule: 'Host(`arkenv.io`)'
        traefik.http.routers.arkenv.entrypoints: 'websecure'
        traefik.http.routers.arkenv.tls.certresolver: 'le'
        traefik.http.services.arkenv.loadbalancer.server.port: '80'

networks:
  public:
    external: true

