name: Deploy Docs
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docs
          push: true
          tags: jeggy/arkenv-docs:latest
      - name: Deploy to Swarm
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ${{ secrets.DOCKER_HOST }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          args: stack deploy --compose-file docs/docker-compose.prod.yml arkenv
